'use strict';

// @flow

// exports
export const WF_REQUEST_LOAD_AUTHENTICATION_DATA_FROM_LOCAL_STORAGE: string = 'WF_REQUEST_LOAD_AUTHENTICATION_DATA_FROM_LOCAL_STORAGE';
export const WF_LOAD_AUTHENTICATION_DATA_FROM_LOCAL_STORAGE: string = 'WF_LOAD_AUTHENTICATION_DATA_FROM_LOCAL_STORAGE';
export const WF_SUCCESS_LOAD_AUTHENTICATION_DATA_FROM_LOCAL_STORAGE: string = 'WF_SUCCESS_LOAD_AUTHENTICATION_DATA_FROM_LOCAL_STORAGE';
export const WF_ERROR_LOAD_AUTHENTICATION_DATA_FROM_LOCAL_STORAGE: string = 'WF_ERROR_LOAD_AUTHENTICATION_DATA_FROM_LOCAL_STORAGE';

export const WF_REQUEST_CHECK_AUTHENTICATION_USER: string = 'WF_REQUEST_CHECK_AUTHENTICATION_USER';
export const WF_CHECK_AUTHENTICATION_USER: string = 'WF_CHECK_AUTHENTICATION_USER';
export const WF_SUCCESS_CHECK_AUTHENTICATION_USER: string = 'WF_SUCCESS_CHECK_AUTHENTICATION_USER';
export const WF_ERROR_CHECK_AUTHENTICATION_USER: string = 'WF_ERROR_CHECK_AUTHENTICATION_USER';

export const WF_REQUEST_REMOVE_AUTHENTICATION_DATA_FROM_LOCAL_STORAGE: string = 'WF_REQUEST_REMOVE_AUTHENTICATION_DATA_FROM_LOCAL_STORAGE';
export const WF_REMOVE_AUTHENTICATION_DATA_FROM_LOCAL_STORAGE: string = 'WF_REMOVE_AUTHENTICATION_DATA_FROM_LOCAL_STORAGE';
export const WF_SUCCESS_REMOVE_AUTHENTICATION_DATA_FROM_LOCAL_STORAGE: string = 'WF_SUCCESS_REMOVE_AUTHENTICATION_DATA_FROM_LOCAL_STORAGE';
export const WF_ERROR_REMOVE_AUTHENTICATION_DATA_FROM_LOCAL_STORAGE: string = 'WF_ERROR_REMOVE_AUTHENTICATION_DATA_FROM_LOCAL_STORAGE';

export const WF_REQUEST_AUTHENTICATE_USER: string = 'WF_REQUEST_AUTHENTICATE_USER';
export const WF_AUTHENTICATE_USER: string = 'WF_AUTHENTICATE_USER';
export const WF_SUCCESS_AUTHENTICATE_USER: string = 'WF_SUCCESS_AUTHENTICATE_USER';
export const WF_ERROR_AUTHENTICATE_USER: string = 'WF_ERROR_AUTHENTICATE_USER';

export const WF_REQUEST_SAVE_AUTHENTICATION_DATA_TO_LOCAL_STORAGE: string = 'WF_REQUEST_SAVE_AUTHENTICATION_DATA_TO_LOCAL_STORAGE';
export const WF_SAVE_AUTHENTICATION_DATA_TO_LOCAL_STORAGE: string = 'WF_SAVE_AUTHENTICATION_DATA_TO_LOCAL_STORAGE';
export const WF_SUCCESS_SAVE_AUTHENTICATION_DATA_TO_LOCAL_STORAGE: string = 'WF_SUCCESS_SAVE_AUTHENTICATION_DATA_TO_LOCAL_STORAGE';
export const WF_ERROR_SAVE_AUTHENTICATION_DATA_TO_LOCAL_STORAGE: string = 'WF_ERROR_SAVE_AUTHENTICATION_DATA_TO_LOCAL_STORAGE';

export const WF_DEAUTHENTICATE_USER: string = 'WF_DEAUTHENTICATE_USER';
export const WF_SUCCESS_DEAUTHENTICATE_USER: string = 'WF_SUCCESS_DEAUTHENTICATE_USER';
export const WF_ERROR_DEAUTHENTICATE_USER: string = 'WF_ERROR_DEAUTHENTICATE_USER';

export const WF_PREPARE_AUTHENTICATION_DATA: string = 'WF_PREPARE_AUTHENTICATION_DATA';